### PR TITLE
team inviter demo

### PR DESCRIPTION
**Pull request by pzduniak**
@patrickxb all using existing APIs!

### CODE REVIEW

**Comment by pzduniak** [comment]
Live demo running as https://keybase.io/kielbase - just dm the bot!

**Comment by pzduniak** [comment]
@malgorithms I'm thinking maybe we could merge this in to showcase the new team API?

**Comment by malgorithms** [comment]
@pzduniak looks great to me!  go for it.

A bonus to the script would be if the bot could add them to multiple channels at once. I think we need to add API support for that though.

**Comment by pzduniak** [comment]
Do you think I should file a ticket for this? It doesn't seem that complicated.

**Pull request merged**
