### PR TITLE
Create / join / leave channel support + read pagination

### PR DESCRIPTION
**Pull request by pzduniak**
Things to consider:
1) How would we test it? Team support seems to be required for this
2) Is it OK to have thousands of channels in a single team, as it will inevitably happen?

### CODE REVIEW

**Comment by malgorithms** [comment]
good q's. One idea might just be a nice full test that does something like these in order:

1. create a random channel
2. list channels and make sure it's there
3. join the channel 
4. list channel's members and make sure we're in there
5. leave the channel
6. list channel's members and make sure we're out of it
7. try to post in the channel and confirm it fails in the way we want (now that we're out of it)
8. delete the random channel
9. list channels and make sure it's gone

this could all be done in the acme team that is declared in the config, so we wouldn't need team creation stuff. But it would need to be able to do all of the above in order. What do you think?

**Comment by pzduniak** [comment]
I actually had no idea that we could delete channels! It's so hidden in the UI (though I guess this is desirable, I wonder how it works internally).

I'm not 100% sure what's the difference between teams and big teams, I guess it's just about the channels count? It looks like we're just missing the channel creation, which would solve #24.

**Comment by pzduniak** [comment]
This is tough, I tried to add deleteConv to the API, but it requires UI or at least some sort of a UI emulator - somehow I also wasn't able to script this out and after a short convo with core we decided to do it next sprint. Did the second best thing, used a static secondary convo to make this work - effectively we're testing out _calling_ the endpoint rather than the endpoint itself, so I think it should be sufficient for this lib.

**Comment by pzduniak** [comment]
What about `join` and `leave`? I left them as-is, is that okay?

**Pull request merged**
